name: Build and Create Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./_site
